version: "3.3"

services:

  tunnetgen:
    build:
        context: https://github.com/VCityTeam/TunNetGen.git
        dockerfile: docker/PureCPP/Dockerfile
    volumes:
      - ./results:/TunNetGenCpp/output
    command: -o output/pc.xyz

  py3dtiles:
    build:
      context: https://gitlab.com/oslandia/py3dtiles.git
      dockerfile: docker/Dockerfile
    command: convert /input/pc.xyz --out /input/3dtiles
    volumes:
      - ./results:/input
    depends_on: 
      tunnetgen:
        condition: service_completed_successfully